some syntax fixes

diff --git a/.github/workflows/build_wheels.yml b/.github/workflows/build_wheels.yml
--- a/.github/workflows/build_wheels.yml
+++ b/.github/workflows/build_wheels.yml
@@ -269,7 +269,7 @@ jobs:
             echo "macOS can handle default cache directory, so don't need to set POOCH_CACHE"
           elif [[ "$RUNNER_OS" == "Windows" ]]; then
             echo "Searching for restored cache directory..."
-            find /c /d -type d -name "${MSF_CACHE_DIR} 2>/dev/null || echo "Cache directory not found"
+            find /c /d -type d -name "${MSF_CACHE_DIR}" 2>/dev/null || echo "Cache directory not found"
             echo "USERPROFILE: ${USERPROFILE}, HOME: ${HOME}"
             echo "POOCH_CACHE=C:\\Users\\runneradmin\\.cache\\${MSF_CACHE_DIR}" >> $GITHUB_ENV
           fi
