try to find location of cache on Windows

diff --git a/.github/workflows/build_wheels.yml b/.github/workflows/build_wheels.yml
--- a/.github/workflows/build_wheels.yml
+++ b/.github/workflows/build_wheels.yml
@@ -268,6 +268,8 @@ jobs:
           elif [[ "$RUNNER_OS" == "macOS" ]]; then
             echo "macOS can handle default cache directory, so don't need to set POOCH_CACHE"
           elif [[ "$RUNNER_OS" == "Windows" ]]; then
+            echo "Searching for restored cache directory..."
+            find /c /d -type d -name "msf-files-3.59.0-alpha" 2>/dev/null || echo "Cache directory not found"
             echo "USERPROFILE: ${USERPROFILE}, HOME: ${HOME}"
             echo "POOCH_CACHE=C:\\Users\\runneradmin\\.cache\\${MSF_CACHE_DIR}" >> $GITHUB_ENV
           fi
